<?php

namespace ContainerKvGPoLE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGatewayControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GatewayController' shared autowired service.
     *
     * @return \App\Controller\GatewayController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/GatewayController.php';

        $container->services['App\\Controller\\GatewayController'] = $instance = new \App\Controller\GatewayController();

        $instance->setContainer(($container->privates['.service_locator.0ghLsew'] ?? $container->load('get_ServiceLocator_0ghLsewService'))->withContext('App\\Controller\\GatewayController', $container));

        return $instance;
    }
}
