<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerREGHRXh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerREGHRXh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerREGHRXh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerREGHRXh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerREGHRXh\App_KernelDevDebugContainer([
    'container.build_hash' => 'REGHRXh',
    'container.build_id' => 'cba1ef1e',
    'container.build_time' => 1659476625,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerREGHRXh');
