<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCRIHKju\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCRIHKju/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCRIHKju.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCRIHKju\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCRIHKju\App_KernelDevDebugContainer([
    'container.build_hash' => 'CRIHKju',
    'container.build_id' => '89c4caaf',
    'container.build_time' => 1658997797,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCRIHKju');
